/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import Koneksi.koneksi;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Pembeli extends javax.swing.JFrame {
    public String kode, nama, jenis_barang, stok, hrg;
    public static int total = 0;
    private Connection conn = new koneksi().connect();
    private DefaultTableModel dtm;

    /**
     * Creates new form Transaksi
     */
    public Pembeli() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = new DefaultTableModel();
        tblTransaksi.setModel(dtm);
         dtm.addColumn("Kode Barang");
         dtm.addColumn("Nama Barang");
         dtm.addColumn("Jenis Barang");
         dtm.addColumn("Jumlah Pembelian");
         dtm.addColumn("Harga");
         dtm.addColumn("Sub Total");
         getData();
    }
    
    public void itemTerpilih(){
        PopUpBarang Pb = new PopUpBarang();
        Pb.trs = this;
        fKode.setText(kode);
        fNama.setText(nama);
        cbJenis.setSelectedItem(jenis_barang); 
        fHarga.setText(hrg);
    }
        
    public void reset(){
        fKode.setText("");
        fNama.setText("");
        fJumlah.setText("");
        fHarga.setText("");
        cbJenis.setSelectedItem("-- Pilih Jenis Barang --");
    }
    
    public void getData(){
        int total = 0;
        try{
            dtm.getDataVector().removeAllElements();
                    String s = "select pembeli.kode_barang, barang.nama_barang, barang.jenis_barang, pembeli.jumlah, barang.harga, pembeli.sub_total from pembeli, barang where pembeli.kode_barang = barang.kd_barang";
                    Statement stat = conn.createStatement();
                    ResultSet rss = stat.executeQuery(s);
                    while(rss.next()){
                        Object[] obj = new Object[7];
                        obj[0] = rss.getString("pembeli.kode_barang");
                        obj[1] = rss.getString("barang.nama_barang");
                        obj[2] = rss.getString("barang.jenis_barang");
                        obj[3] = rss.getString("pembeli.jumlah");
                        obj[4] = rss.getInt("barang.harga");
                        obj[5] = rss.getInt("pembeli.sub_total");
                        dtm.addRow(obj);
                    }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }
    
    public static void setTotal(int tot){
        total = total+tot;
    }
    
    public static int getTotal(){
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        fHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        bSimpan = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fJumlah = new javax.swing.JTextField();
        bHapus = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        bBayar = new javax.swing.JButton();
        bKembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fTotal = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        TRANSAKSI PEMBELI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE BARANG");

        fKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKodeKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA BARANG");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS BARANG");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Jenis Barang --", "Rem, Perlengkapan", "Wiper Mobil", "Spare Part", "Filter Mobil" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HARGA BARANG");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bEdit.setText("UBAH");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JUMLAH");

        fJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fJumlahKeyPressed(evt);
            }
        });

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bBatal.setText("BATAL");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bBayar.setText("BAYAR");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bKembali.setText("KEMBALI");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL");

        bCari.setText("CARI");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bKembali)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(bSimpan)
                .addGap(18, 18, 18)
                .addComponent(bEdit)
                .addGap(14, 14, 14)
                .addComponent(bHapus)
                .addGap(18, 18, 18)
                .addComponent(bBatal)
                .addGap(18, 18, 18)
                .addComponent(bBayar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(fJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fKode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCari)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSimpan)
                            .addComponent(bEdit)
                            .addComponent(bHapus)
                            .addComponent(bBatal)
                            .addComponent(bBayar))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCari)))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // Untuk kembali ke menu utama
        new Menu_Utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bKembaliActionPerformed

    private void fKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKodeKeyPressed
        // Ketika kode barang dienter maka :
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String sql = "select * from barang where kd_barang like '"+fKode.getText()+"%'";
            try{
                Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while(hasil.next()){
                   fNama.setText(hasil.getString(2));
                   fHarga.setText(hasil.getString(4));
                   cbJenis.setSelectedItem(hasil.getString(3));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
            }
        }
    }//GEN-LAST:event_fKodeKeyPressed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // Tombol Batal
        reset();
    }//GEN-LAST:event_bBatalActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // Tombol Simpan
            String kode = fKode.getText();
            String namabarang = fNama.getText();
            String jmlh = fJumlah.getText();
            String hrg = fHarga.getText();
            int jumlah = Integer.parseInt(jmlh);
            int harga = Integer.parseInt(hrg);
            String jenis = cbJenis.getSelectedItem().toString();
            String zsql = "select id_transaksi from transaksi order by id_transaksi desc LIMIT 1";
            try{
                Statement state = conn.createStatement();
                ResultSet rs = state.executeQuery(zsql);
                
                while(rs.next()){
                    String id = rs.getString("id_transaksi").substring(3);
                    int transaksi = Integer.parseInt(id) + 1;
                    String Nol = "";
                    
                    if(transaksi<10){
                        Nol = "00";
                    }else if(transaksi<100){
                        Nol = "0";
                    }else if(transaksi<1000){
                        Nol = "";
                    }
                                       
                    String id_transaksi = "TRS" + Nol + transaksi;
                    int subtotal = jumlah*harga;
                    String st = String.valueOf(subtotal);
                    int total = 0;
                    total += subtotal;
                    setTotal(total);
                    String sql = "insert into pembeli values('"+id_transaksi+"','"+kode+"','"+jmlh+"', '"+st+"')";
                    try{
                        Statement stat = conn.createStatement();
                        stat.executeUpdate(sql);
                        getData();
                        JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
            String zql = "select stok from barang where kd_barang='"+fKode.getText()+"'";
            try{
                Statement stat = conn.createStatement();
                ResultSet rs = stat.executeQuery(zql);
                while(rs.next()){
                    String stok = rs.getString("stok");
                    int istok = Integer.parseInt(stok);
                    int st = istok-Integer.parseInt(fJumlah.getText());
                    String s = "update barang set stok=? where kd_barang='"+fKode.getText()+"'";
                    try{
                        PreparedStatement stt = conn.prepareStatement(s);
                        stt.setInt(1, st);
                        stt.executeUpdate();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // Tombol Edit
         String jmlh = fJumlah.getText();
         String hrg = fHarga.getText();
         int jumlah = Integer.parseInt(jmlh);
         int harga = Integer.parseInt(hrg);
         int subtotal = jumlah*harga;
         String sql = "update pembeli set jumlah=?, sub_total=? where kode_barang='"+fKode.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, jumlah);
            stat.setInt(2, subtotal);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            getData();
            reset();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "data gagal diubah "+e);
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tblTransaksi.getSelectedRow();
        String a = dtm.getValueAt(baris, 0).toString();
        String b = dtm.getValueAt(baris, 1).toString();
        String c = dtm.getValueAt(baris, 2).toString();
        String d = dtm.getValueAt(baris, 3).toString();
        String e = dtm.getValueAt(baris, 4).toString();

        fKode.setText(a);
        fNama.setText(b);
        cbJenis.setSelectedItem(c);
        fJumlah.setText(d);
        fHarga.setText(e);
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // Tombol Hapus
        int row = tblTransaksi.getSelectedRow();
        String selected = dtm.getValueAt(row,0).toString();
        try{
            PreparedStatement ps = conn.prepareStatement("delete from pembeli where kode_barang='"+selected+"'");
            ps.executeUpdate();
            dtm.removeRow(row);
            reset();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        // Ke Menu Transaksi
        Transaksi trans = new Transaksi();
        trans.byr = this;
        trans.setVisible(true);
        trans.setResizable(false);
    }//GEN-LAST:event_bBayarActionPerformed

    private void fJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fJumlahKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        String jumlah = fJumlah.getText();
        String harga = fHarga.getText();
        int jmlh = Integer.parseInt(jumlah);
        int hrg = Integer.parseInt(harga);
            int total = jmlh*hrg;
            String tot = String.valueOf(total);
            fTotal.setText(tot);
        }
    }//GEN-LAST:event_fJumlahKeyPressed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        PopUpBarang Pb = new PopUpBarang();
        Pb.trs = this;
        Pb.setVisible(true);
        Pb.setResizable(false);
    }//GEN-LAST:event_bCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox cbJenis;
    private javax.swing.JTextField fHarga;
    private javax.swing.JTextField fJumlah;
    private javax.swing.JTextField fKode;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField fTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    // End of variables declaration//GEN-END:variables
}
